### ISSUE TITLE
Not enough random bits for the town name generation (40 needed, 32 available)

### ISSUE THREAD

**Issue by ZvikaZ** [OpenTTD/nml#229] opened 2021-08-04 14:40 UTC
Hi.

I've tried creating a simple town name generator, with a real list of Israeli names.
But it fails with 

     nmlc ERROR: "israel.nml", line 10: Not enough random bits for the town name generation (40 needed, 32 available)

If I comment out most of the names, and leave only few hundreds, it succeeds.

My code is at https://github.com/ZvikaZ/OpenTTD-Israeli-Town-Names , and compiles simply with `nmlc.exe israel.nml`. I tried both nml-standalone-0.5.3-win64 at Windows, and latest pip at Linux.

I've tried searching for other town name generators, to see how others handled similar situation, and found https://github.com/GameMaker2k/NorthEast-Towns , which has much more names that my generator. However, it also fails with the same error. Maybe it's a regression on the compiler side?

**Comment by FLHerne** [comment] 2021-08-04 14:42
This is probably a duplicate of #184. It's been fixed in master by #185.

**Comment by ZvikaZ** [comment] 2021-08-04 14:48
Thanks for the quick reply!
Are there any plans to make a new release? After all, it's been fixed since January :-)

**Comment by glx22** [comment] 2021-08-15 20:30
Closing the issue as 0.6.0 is now released.

**Closed by glx22** 2021-08-15 20:30 UTC
