### ISSUE TITLE
Speed values are slightly off when using metric units

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/nml#74] opened 2019-12-20 08:27 UTC
Note: I'm using the (very) old NML executable for Windows to make an NRT roadset, if that makes a difference. I don't _think_ anything has been changed to this effect lately, but just in case, I wanted to mention it.

**Expected Result**

When defining speeds for some feature in km/h or m/s, the in-game speeds should be exactly as defined.

**Actual Result**

The displayed speeds in-game are slightly different than what is defined by the NewGRF. As an example, I've attached a simple NewGRF (and NML file) which clearly defines a roadtype with a speed of 50 km/h; however in-game the speed is reported as 49 km/h. A similar effect is observed with m/s.

This feels like some kind of rounding error or something, perhaps due to the weird units OpenTTD uses internally, but that's just an uneducated guess 🤷‍♂ Whatever the case, this probably affects other things as well, but I haven't tested that to find out.

[speedbug.zip](https://github.com/OpenTTD/nml/files/3987333/speedbug.zip)

**Comment by planetmaker** [comment] 2019-12-20 09:40
This probably is a duplicate of https://github.com/OpenTTD/nml/pull/35 or solved by that

**Closed** 2020-05-05 20:46 UTC
